### ISSUE TITLE
debug stuck on with linux?

### ISSUE THREAD

**Issue by GWustenstein** [uhppoted/uhppoted-dll#2]
I don't know about this one, but building on debian/pi it seems to ignore the debug flag (set to false, driver still outputs debug messages) but the windows platform it does not.  I'm still chasing down if I have something funky in my env or not, or if the windows build didn't actually build the new version, but scratching my head on this one...
Python bindings, FWIW

**Comment by uhppoted** [comment]
Hmm, just tried this out and I get the expected behaviour (you're using _Python_ as far as I remember ?):

_With [`debug = True`](https://github.com/uhppoted/uhppoted-dll/blob/master/examples/python/examples.py#L205):_
```
 make get-device
yapf -ri .
yapf -ri ../../bindings/python
GODEBUG=cgocheck=2 && export LD_LIBRARY_PATH=../../lib && python3 examples.py  get-device
Namespace(command='get-device', controller=405419896, ip_address='155.138.141.23', subnet_mask='255.255.255.0', gateway_address='155.138.141.23', listener_address='155.138.141.23', card=8000001, card_index=7, door=4, event_index=43, time_profile=29)
 ... request
 ...          00000000  17 94 00 00 78 37 2a 18  00 00 00 00 00 00 00 00  |....x7*.........|
 ...          00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          

 ... sent 64 bytes to 155.138.141.23:60000

 ... received 64 bytes from 155.138.141.23:60000
 ...          00000000  17 94 00 00 78 37 2a 18  c0 a8 01 64 ff ff ff 00  |....x7*....d....|
 ...          00000010  c0 a8 01 01 00 12 23 34  45 56 08 92 20 18 11 05  |......#4EV.. ...|
 ...          00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
 ...          
get-device
  ID               405419896
  IP address       192.168.1.100
  subnet mask      255.255.255.0
  gateway address  192.168.1.1
  MAC              00:12:23:34:45:56
  version          v8.92
  released         2018-11-05
```

_With [`debug = False`](https://github.com/uhppoted/uhppoted-dll/blob/master/examples/python/examples.py#L205):_
```
make get-device
yapf -ri .
yapf -ri ../../bindings/python
GODEBUG=cgocheck=2 && export LD_LIBRARY_PATH=../../lib && python3 examples.py  get-device
Namespace(command='get-device', controller=405419896, ip_address='155.138.141.23', subnet_mask='255.255.255.0', gateway_address='155.138.141.23', listener_address='155.138.141.23', card=8000001, card_index=7, door=4, event_index=43, time_profile=29)
get-device
  ID               405419896
  IP address       192.168.1.100
  subnet mask      255.255.255.0
  gateway address  192.168.1.1
  MAC              00:12:23:34:45:56
  version          v8.92
  released         2018-11-05
```

Didn't do anything special:
- Built _uhppoted-dll_ on a clean Debian 11 x64 (bullseye) VPS
- Updated the IP addresses in [examples.py](https://github.com/uhppoted/uhppoted-dll/blob/master/examples/python/examples.py)
- Updated the _Makefile_ to use python3

One thing to check perhaps:
- [examples.py](https://github.com/uhppoted/uhppoted-dll/blob/master/examples/python/examples.py) doesn't take `--debug` as a command line argument (because it's an example and not a fully fledged app) so you have to set it in the source code.

**Comment by GWustenstein** [comment]
Oof, that face when knowing I'm going to loose a day resolving build env issues, lol...
documenting, mostly for my own sanity:
Pi:  Bullseye, GCC 10.2.1, Go v 19.2 linux/arm, Python 3.9.2
Win10: GCC 4.9.2, Go v 19.1  win/amd64, Python 3.10.2

Went so far as finding the following line:
        u = uhppoted.Uhppote(
            uhppote=uhppoted.UHPPOTE(bind, broadcast, listen, timeout, controllers, debug))
replaced debug with 'foo', no typechecking at all, still prints like a banshee.

Closing this assuming something rotten on my Pi's install, unless I find something *really* weird with the app...

**Comment by uhppoted** [comment]
It's probably something so obvious you just can't see it :-) :-).

(BTW _C_ treats anything that is not _0_ as _true_ - so it's possible the _foo_ is just another _true_)

Some things to try:
- setting debug in the actual Python [binding](https://github.com/uhppoted/uhppoted-dll/blob/master/bindings/python/uhppoted.py#L186-L193)
```
class Uhppote:

    def __init__(self, uhppote=None):
        self.ffi = FFI(self.errcheck)
        self._uhppote = None
        if uhppote:
            self._uhppote = GoUHPPOTE(uhppote.bind, uhppote.broadcast, uhppote.listen,
                                      uhppote.timeout, uhppote.controllers, uhppote.debug)

```

- setting it false in the DLL [here](https://github.com/uhppoted/uhppoted-dll/blob/master/go/main.go#L465) or [here](https://github.com/uhppoted/uhppoted-dll/blob/master/go/main.go#L485)
```
...
		debug = bool(u.debug)
                ...
                ...
	DEBUG = debug
...
```

**Comment by GWustenstein** [comment]
Finally had a few moments to play with this...
Replacing uhppote.debug with False in the python binding still prints debug messages (!)
Replacing u.debug with false and recompiling the libs does in fact kill off the debugs.
Next step is to add a couple lines of code to print the inbound variable type when called to see what the hell is happening, though methinks this is now a 3.10.2 thingie

**Comment by uhppoted** [comment]
I've just quickly tried it on Debian 11 with Python 3.10.8 and it was ok.

Possibly dumb question - what version of Go do you have installed?
```
go version
```

The reason I'm asking is that the version of Go installed by `apt install golang` is 1.15 which is **ancient** - the latest and greatest is 1.19.

**Comment by uhppoted** [comment]
BTW, I would really like to get to the bottom of this .. but if you're stuck and just want to get something working, [uhppoted-codegen](https://github.com/uhppoted/uhppoted-codegen) has a set of generated bindings that are straight [Python](https://github.com/uhppoted/uhppoted-codegen/tree/main/bindings/python) i.e. no DLL weirdness.

A bit less tested and proven though ...

**Comment by GWustenstein** [comment]
I'm using golang 19.2 on this pi, but it should not make a difference.  Just forced it to false in main.go, built it, and called it a day (at least until something else breaks;^)

**Comment by GWustenstein** [comment]
I built uhppoted-codegen, then refactored my event processing code to use the native python driver.  Most of the refactoring had to do with somewhat different attribute namespaces, and python-native datetime objects, the latter of which cleaned up my code quite a bit since I'm doing a lot of event correlation.

I'll be using this going forward...

**Comment by uhppoted** [comment]
Great! 

The pre-built bindings on the [releases page](https://github.com/uhppoted/uhppoted-codegen/releases/tag/v0.8.2) would have saved you some effort - I'll link to them from the README.

**Comment by GWustenstein** [comment]
It was more about doing a trial before sticking it in the lib, and doing the build I can see if there are any hiccups in the environment that I missed when blindly doing the DLL; I think it took about a minute to build so it was not an issue.  There is something weird on this particular pi and it might be because it was upgraded from Buster to Bullseye, folks are saying clean installs work better

**Comment by uhppoted** [comment]
Reopening this for further investigation - there's a possibility it might have something to do with _struct_ packing on ARM, which would point to a possible bug in the _cgo_ compiler.

**Comment by GWustenstein** [comment]
Well, that would explain a lot.  I've since been running the native python driver built from codegen.  Got another issue related to UDP (timeouts without a retry mechanism) that I'm going to log as a separate issue which seems to be present in both DLL and codegen builds, suspect it's just an oversight.

**Comment by uhppoted** [comment]
Having finally got my hands on a RaspberryPi - it appears there is a definite problem on the Pi at least, and possibly ARM in general. On the _Pi Model 3B+_, `debug` is stuck `off`:
```
$ make get-device
GODEBUG=cgocheck=2 && export LD_LIBRARY_PATH=../../lib && python examples.py  get-device
>>> DEBUG True
>>> debug:: &{bind:0x76548db0 broadcast:0x43bb79f0 listen:0x43bb7a10 timeout:2500 devices:<nil> debug:false _:[0 0 0]}

get-device
  ID               405419896
...
```

The _C_ and _C++_ interfaces still work correctly though so it's starting to look like it may be something in the Python _ctypes_ implementation.

**Comment by uhppoted** [comment]
Seems to be something related to the packing of the `controllers` list in the `UHPPOTE` _struct_ on ARM:
- The packed _struct_ is 28 bytes when it should be 24
- The controller list pointer is being packed as 64 bytes when it should be 32 bytes
- The `debug` flag is a civilian casualty - it's now in the wrong place at the wrong time.

Memory dumps:
```
# Empty controllers list (ARM7)

GOOS:       linux
GOARCH:   arm

UHPPOTE: {bind:0x654b4a68 broadcast:0x654bd390 listen:0x654bd3b0 timeout:2500 devices:<nil> debug:false _:[0 0 0]}

         bind:      0x654b4a68  0.0.0.0
         broadcast: 0x654bd390  255.255.255.255
         listen:    0x654bd3b0  0.0.0.0:60001
         timeout:   0x000009c4  2500
         devices:   0x00000000  <nil>
         debug:                 false

00000000  68 4a 4b 65 90 d3 4b 65  b0 d3 4b 65 c4 09 00 00  |hJKe..Ke..Ke....|
00000010  00 00 00 00 00 00 00 00  01 00 00 00              |............|

>        bind:      0x654b4a68
>        broadcast: 0x654bd390
>        listen:    0x654bd3b0
>        timeout:   0x9c4  2500
>        devices:   0x0
>        debug:     0x0
```

```
# `controllers` list with two entries (ARM7)

GOOS:     linux
GOARCH:   arm

UHPPOTE: {bind:0x65661ae0 broadcast:0x656694f0 listen:0x65669510 timeout:2500 devices:<nil> debug:true _:[74 102 101]}

         bind:      0x65661ae0  0.0.0.0
         broadcast: 0x656694f0  255.255.255.255
         listen:    0x65669510  0.0.0.0:60001
         timeout:   0x000009c4  2500
         devices:   0x00000000  <nil>
         debug:                 true

00000000  e0 1a 66 65 f0 94 66 65  10 95 66 65 c4 09 00 00  |..fe..fe..fe....|
00000010  00 00 00 00 70 4a 66 65  01 00 00 00              |....pJfe....|

>        bind:      0x65661ae0
>        broadcast: 0x656694f0
>        listen:    0x65669510
>        timeout:   0x9c4  2500
>        devices:   0x0
>        debug:     0x65664a70
```

```
# Empty controllers list (AMD64)

GOOS:     darwin
GOARCH:   amd64

UHPPOTE: {bind:0x7fb8a9d9ad40 broadcast:0x7fb8a9d9ad70 listen:0x7fb8a9d9ada0 timeout:2500 devices:<nil> debug:true _:[0 0 0 0 0 0 0]}

         bind:      0x7fb8a9d9ad40  0.0.0.0
         broadcast: 0x7fb8a9d9ad70  255.255.255.255
         listen:    0x7fb8a9d9ada0  0.0.0.0:60001
         timeout:   0x000009c4  2500
         devices:   0x00000000  <nil>
         debug:                 true

00000000  40 ad d9 a9 b8 7f 00 00  70 ad d9 a9 b8 7f 00 00  |@.......p.......|
00000010  a0 ad d9 a9 b8 7f 00 00  c4 09 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00  |................|

>        bind:      0x7fb8a9d9ad40
>        broadcast: 0x7fb8a9d9ad70
>        listen:    0x7fb8a9d9ada0
>        timeout:   0x9c4  2500
>        devices:   0x0
>        debug:     0x1
```

```
# Controllers list with two entries (AMD64)

GOOS:     darwin
GOARCH:   amd64
compiler: gc
file:     main.go

UHPPOTE: {bind:0x7f8fc968ef80 broadcast:0x7f8fc968efb0 listen:0x7f8fc968efe0 timeout:2500 devices:0x7f8fc9672c10 debug:true _:[0 0 0 0 0 0 0]}

         bind:      0x00007f8fc968ef80  0.0.0.0
         broadcast: 0x00007f8fc968efb0  255.255.255.255
         listen:    0x00007f8fc968efe0  0.0.0.0:60001
         timeout:   0x00000000000009c4  2500
         devices:   0x&{0000000000000002 00007f8fc9667870}  &{2 0x7f8fc9667870}
         debug:                         true

00000000  80 ef 68 c9 8f 7f 00 00  b0 ef 68 c9 8f 7f 00 00  |..h.......h.....|
00000010  e0 ef 68 c9 8f 7f 00 00  c4 09 00 00 00 00 00 00  |..h.............|
00000020  10 2c 67 c9 8f 7f 00 00  01 00 00 00 00 00 00 00  |.,g.............|

>        bind:      0x7f8fc968ef80
>        broadcast: 0x7f8fc968efb0
>        listen:    0x7f8fc968efe0
>        timeout:   0x9c4  2500
>        devices:   0x7f8fc9672c10
>        debug:     0x1
```

**Comment by uhppoted** [comment]
Gotit!! There is an extra field [`ndevices`](https://github.com/uhppoted/uhppoted-dll/blob/master/bindings/python/uhppoted.py#L653) in the _Python_ bindings declaration of the `UHPPOTE` _struct_, left over from an earlier
version of the FFI (because .. C#):
```
class GoUHPPOTE(Structure):
    _fields_ = [('bind', c_char_p), ('broadcast', c_char_p), ('listen', c_char_p),
                ('timeout', c_int), ('ndevices', c_int), ('devices', POINTER(GoControllers)),
                ('debug', c_bool)]
...
```

Python on i386 architectures seems to pack _structs_ on 32-bit word boundaries and the extra field is surrounded by 64-bit pointers so it was ignored:
```
ndevices = 0x00123456
...
00000000  e0 dc 7a 4a 8b 7f 00 00  10 dd 7a 4a 8b 7f 00 00
00000010  40 dd 7a 4a 8b 7f 00 00  c4 09 00 00 56 34 12 00
00000020  90 db 78 4a 8b 7f 00 00  00 00 00 00 00 00 00 00
```

On 32-bit ARM, pointers are 32-bits and the `ndevices` field shows up as an unexpected field and offsets the `debug` value by a 32-bit word:
```
ndevices = 0x00123456
...
00000000  e0 fa 67 65 10 c3 68 65  30 c3 68 65 c4 09 00 00
00000010  56 34 12 00 00 00 00 00  01 00 00 00
```

_TO BE CONFIRMED: presumably Python on ARM64 doesn't pack on 32-bit boundaries which is why the issue shows up on the RaspberryPi 4._

**Comment by uhppoted** [comment]
Provisional fix pushed to `master` branch.

#### TODO
- [ ] Confirm on ARM64
- [ ] Confirm on Raspberry Pi 4 with 64-bit _Raspbian_
- [ ] C: add UHPPOTE _struct_ test
- [ ] C++: add UHPPOTE _struct_ test
- [ ] C#: add UHPPOTE _struct_ test
- [ ] Python: add UHPPOTE _struct_ test
- [ ] CCL#: add UHPPOTE _struct_ test

**Comment by uhppoted** [comment]
Confirmed fix on ARM64:
```
$ uname -a
Linux uhppoted-dll 5.18.0-0.deb11.4-cloud-arm64 #1 SMP Debian 5.18.16-1~bpo11+1 (2022-08-12) aarch64 GNU/Linux

$ make all
yapf -ri .
yapf -ri ../../bindings/python
GODEBUG=cgocheck=2 && export LD_LIBRARY_PATH=../../lib/tests && python3 tests.py  all
get-devices           ok
get-device            ok
set-address           ok
get-status            ok
get-time              ok
set-time              ok
get-listener          ok
set-listener          ok
get-door-control      ok
set-door-control      ok
open-door             ok
get-cards             ok
get-card              ok
get-card-by-index     ok
put-card              ok
delete-card           ok
delete-cards          ok
get-event-index       ok
set-event-index       ok
get-event             ok
record-special-events ok
get-time-profile      ok
set-time-profile      ok
clear-time-profiles   ok
set-time-profile      ok
refresh-tasklist      ok
clear-tasklist        ok
lookup                ok
structs               ok
uhppoted@uhppoted-dll:/opt/uhppoted/uhppoted-dll/tests/python$ 
```

**Comment by uhppoted** [comment]
Confirmed fix on ARM32 (RaspberryPi 3B+):
```
> /opt/uhppoted/uhppoted-dll/tests/python $ uname -a
Linux phil 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux

> /opt/uhppoted/uhppoted-dll/tests/python $ make all
yapf -ri .
yapf -ri ../../bindings/python
GODEBUG=cgocheck=2 && export LD_LIBRARY_PATH=../../lib/tests && python tests.py  all
get-devices           ok
get-device            ok
set-address           ok
get-status            ok
get-time              ok
set-time              ok
get-listener          ok
set-listener          ok
get-door-control      ok
set-door-control      ok
open-door             ok
get-cards             ok
get-card              ok
get-card-by-index     ok
put-card              ok
delete-card           ok
delete-cards          ok
get-event-index       ok
set-event-index       ok
get-event             ok
record-special-events ok
get-time-profile      ok
set-time-profile      ok
clear-time-profiles   ok
set-time-profile      ok
refresh-tasklist      ok
clear-tasklist        ok
lookup                ok
structs               ok
uhppoted@phil:/opt/uhppoted/uhppoted-dll/tests/python $ 
```

**Comment by uhppoted** [comment]
Hi,

Any chance you could check the fix on the Raspberry Pi 4? I don't have one to hand and they're like hen's teeth at the moment - you would just need to build the latest and run the Python tests:
```
git clone https://github.com/uhppoted/uhppoted-dll.git
cd uhppoted-dll
make build
cd tests/python
make all
```

**Comment by uhppoted** [comment]
That would be awesome! Thanks!

**Comment by GWustenstein** [comment]
The last couple days have been crazy; really busy, then today a huge storm blowing through knocking out power several times today hitting various points of my tunnel relay as well as nodes in my wifi mesh.  Finally had a few minutes after dinner to build and test, other than the issue with make tests below, running examples.py with the debug flag set to either True or False does the expected behavior on RPi4!  So, now, your bit-packing worries are over;)

make all in tests/python fails, btw...
:~/uhppoted-dll $ cd tests/python
:~/uhppoted-dll/tests/python $ make all
yapf -ri .
: No such file or directory
make: *** [Makefile:17: format] Error 127
:~/uhppoted-dll/tests/python $ ls
total 36
drwxr-xr-x 2   4096 Nov  4 21:23 .
drwxr-xr-x 7   4096 Nov  4 21:23 ..
-rw-r--r-- 1   1759 Nov  4 21:23 Makefile
-rw-r--r-- 1     47 Nov  4 21:23 .style.yapf
-rwxr-xr-x 1  18077 Nov  4 21:23 tests.py
:~/uhppoted-dll/tests/python $

**Comment by uhppoted** [comment]
Oh, **great**!! Thank you so much - really appreciated!

That was a **good** bug :-) ... closing as fixed.
